"""Meeting data models."""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class MeetingPlatform(str, Enum):
    ZOOM = "zoom"
    GOOGLE_MEET = "google_meet"
    TEAMS = "teams"


class MeetingStatus(str, Enum):
    PENDING = "pending"
    JOINING = "joining"
    ACTIVE = "active"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class TranscriptSegment(BaseModel):
    """A single segment of transcribed speech."""

    speaker: str = Field(description="Speaker name or identifier")
    text: str = Field(description="Transcribed text content")
    timestamp: float = Field(description="Seconds since meeting start")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)

    @property
    def timestamp_display(self) -> str:
        mins = int(self.timestamp // 60)
        secs = int(self.timestamp % 60)
        return f"{mins:02d}:{secs:02d}"


class ActionItem(BaseModel):
    """An action item extracted from the meeting."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    description: str
    assignee: Optional[str] = None
    deadline: Optional[str] = None
    source_text: str = Field(description="The transcript text this was extracted from")
    timestamp: float = 0.0


class Decision(BaseModel):
    """A decision made during the meeting."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    description: str
    context: str = ""
    participants_involved: list[str] = Field(default_factory=list)
    timestamp: float = 0.0


class ChatMessage(BaseModel):
    """A message to post in the meeting chat."""

    content: str
    message_type: str = Field(
        default="insight",
        description="Type: insight, research, action_item, summary",
    )
    timestamp: float = 0.0


class TopicDetection(BaseModel):
    """A topic detected in the conversation."""

    topic: str
    first_mentioned: float = 0.0
    mentions: int = 1
    related_segments: list[int] = Field(default_factory=list)


class MeetingInsight(BaseModel):
    """Real-time insight generated by the AI during the meeting."""

    insight_type: str = Field(
        description="Type: topic_shift, action_item, decision, research_finding, key_point"
    )
    content: str
    confidence: float = Field(default=0.8, ge=0.0, le=1.0)
    should_post_to_chat: bool = False
    chat_message: Optional[str] = None
    timestamp: float = 0.0


class Meeting(BaseModel):
    """Complete meeting record."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    meeting_url: str
    platform: MeetingPlatform = MeetingPlatform.ZOOM
    status: MeetingStatus = MeetingStatus.PENDING
    bot_id: Optional[str] = None
    bot_display_name: str = "Pyonair AI"

    title: Optional[str] = None
    host: Optional[str] = None
    participants: list[str] = Field(default_factory=list)

    transcript: list[TranscriptSegment] = Field(default_factory=list)
    action_items: list[ActionItem] = Field(default_factory=list)
    decisions: list[Decision] = Field(default_factory=list)
    topics: list[TopicDetection] = Field(default_factory=list)
    insights: list[MeetingInsight] = Field(default_factory=list)
    chat_messages_sent: list[ChatMessage] = Field(default_factory=list)

    started_at: Optional[datetime] = None
    ended_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    summary: Optional[str] = None

    @property
    def duration_minutes(self) -> Optional[float]:
        if self.started_at and self.ended_at:
            return (self.ended_at - self.started_at).total_seconds() / 60
        return None

    @property
    def transcript_text(self) -> str:
        return "\n".join(
            f"[{seg.timestamp_display}] {seg.speaker}: {seg.text}"
            for seg in self.transcript
        )


class JoinMeetingRequest(BaseModel):
    """API request to join a meeting."""

    meeting_url: str = Field(description="Zoom/Meet/Teams meeting URL")
    bot_name: Optional[str] = Field(
        default=None, description="Custom bot display name"
    )
    auto_summary: bool = Field(
        default=True, description="Generate summary when meeting ends"
    )
    real_time_chat: bool = Field(
        default=True, description="Post insights to meeting chat in real time"
    )


class JoinMeetingResponse(BaseModel):
    """API response after requesting to join a meeting."""

    meeting_id: str
    status: MeetingStatus
    bot_id: Optional[str] = None
    message: str


class MeetingSummary(BaseModel):
    """Post-meeting summary."""

    meeting_id: str
    title: str
    duration_minutes: float
    participant_count: int
    participants: list[str]
    executive_summary: str
    key_topics: list[str]
    action_items: list[ActionItem]
    decisions: list[Decision]
    full_transcript: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)
